[phases.build]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader"
]

[phases.start]
cmd = "node /assets/scripts/prestart.mjs /assets/nginx.template.conf /nginx.conf && rm -f .env bootstrap/cache/config.php && php artisan config:clear && php artisan migrate --force || true && php artisan storage:link || true && php artisan optimize && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf -g 'daemon off;')"
