[phases.build]
cmds = [
  "composer install --optimize-autoloader --no-scripts --no-interaction",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[phases.start]
cmd = "php -d variables_order=EGPCS -S 0.0.0.0:${PORT} -t public public/index.php"
