[phases.build]
cmds = [
  "composer install --optimize-autoloader --no-scripts --no-interaction",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "php artisan migrate --force"
]

