[phases.install]
cmds = [
  "composer install --no-dev --prefer-dist --optimize-autoloader"
]

[phases.build]
cmds = [
  "php artisan storage:link || true",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "bash -lc 'set -euo pipefail; php artisan config:clear; 
php artisan migrate --force --no-interaction --isolated || true; php artisan optimize; php-fpm -F & nginx -g \"daemon off;\"'"
