[phases.install]
cmds = [
  "composer install --no-dev --prefer-dist --optimize-autoloader"
]

[phases.build]
cmds = [
  "php artisan storage:link || true",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "bash -lc 'php artisan migrate --force --no-interaction || true; php -S 0.0.0.0:$PORT -t public public/index.php'"

