[phases.setup]
nixPkgs = [
  "php82",
  "php82Composer",
  "php82Extensions.bcmath",
  "php82Extensions.curl",
  "php82Extensions.fileinfo",
  "php82Extensions.mbstring",
  "php82Extensions.openssl",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "php82Extensions.dom"
]

[phases.build]
cmds = ["composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction --no-scripts"]

[start]
cmd = "php artisan migrate --force && php artisan storage:link || true && php artisan config:cache && php artisan route:cache && php artisan view:cache && php -S 0.0.0.0:$PORT -t public"
