[phases.install]
cmds = [
  "composer install --no-dev --prefer-dist --optimize-autoloader"
]

[phases.build]
cmds = [
  "php artisan storage:link || true"
]

[start]
cmd = "bash -lc 'set -euo pipefail; php artisan config:clear; php artisan migrate --force --no-interaction --isolated || true; php artisan optimize; mkdir -p /var/log/nginx /var/cache/nginx; rm -f /var/log/nginx/access.log /var/log/nginx/error.log; ln -s /dev/stdout /var/log/nginx/access.log; ln -s /dev/stderr /var/log/nginx/error.log; if [ -x /assets/php-nginx-start.sh ]; then /assets/php-nginx-start.sh; else php-fpm -F & nginx -g \"daemon off;\"; fi'"
