[phases.build]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader"
]

[phases.start]
cmd = "composer install && php artisan optimize && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force"
